# Generated by Django 4.2.2 on 2023-07-04 15:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('release_date', models.DateTimeField()),
                ('client', models.ForeignKey(default=None, limit_choices_to={'user_type': 'client'}, on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='core.profile')),
            ],
        ),
    ]
